[package]
name = "dbvi"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Terminal database viewer for vim users"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
sqlx = "0.8.6"
